language: python

python:
- '2.7'
- '3.5'
- '3.6'

os:
- linux
- osx

branches:
  only:
  - master
  - reconfigure_ci

install:
- sudo apt-get update

# Here we install Anaconda to work with Virtual Environments.
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no

# Adding AstroConda Channel since it contains most of the dependencies for Dragons and Dragons-SOAR
- conda config --add channels http://ssb.stsci.edu/astroconda
- conda update -q conda

# Useful for debugging any issues with conda
- conda info -a

# Create astroconda virtual environment
- conda env create -q python=$TRAVIS_PYTHON_VERSION -f environment.yml
- source activate samfptools

