name: samfptools
channels:
  - astroconda
dependencies:
  - astropy
  - astroconda::ccdproc
  - configparser
  - dateutil
  - matplotlib
  - pandas
  - pip
  - scipy
  - pip:
    - future
    - coveralls
