#!/usr/bin/env python

import argparse
import samfp

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description="Combine images into a merged single file."
    )

    parser.add_argument('input_files', nargs='+')

    parser.add_argument('-D', '--debug', action='store_true',
        help="Turn on DEBUG mode (overwrite quiet mode).")

    parser.add_argument('-q', '--quiet', action='store_true',
        help="Run the script without printing anything.")

    parser.add_argument('-o', '--output', type=str, default=None,
        help='Name of the output fits file.')

    args = parser.parse_args()
    flat_combine = samfp.FlatCombine(args.input_files,
                                     verbose=not args.quiet, debug=args.debug)
    flat_combine.run()


