#!/usr/bin/env python 
# -*- coding: utf8 -*-

from samfp import wcal

__author__ = 'Bruno Quint'

if __name__ == '__main__':

    args = wcal.parse_arguments()

    wavelength_calibration = wcal.WavelengthCalibration(
        args.filename,
        args.gap_size,
        debug_mode=args.debug,
        output=args.output,
        verbose_mode=not args.quiet
    )

    wavelength_calibration.start()
    wavelength_calibration.join()

    if wavelength_calibration.is_alive():
        wavelength_calibration.log.warn(" A thread is still running.")
    else:
        wavelength_calibration.log.info(" All done.")