#!/usr/bin/env python
import sys

try:
    import samfp
except ImportError:
    print(
        "Please, check if you have samfp installed or if you are within the " +
        "Virtual Environment where it was installed.")
    print("Leaving now.")
    sys.exit()

if __name__ == '__main__':
    samfp.mkcube.main()
